### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fordrink** [garlic0x1/php-analyzer#1]
How to resolve this problem?
![Uploading 2022-07-12_00-21.png…]()

**Comment by garlic0x1** [comment]
Can you give any information? Your link is broken.
You should be able to clone the package and run with cargo

**Comment by garlic0x1** [comment]
Can you give any information? That image link is broken.
You should be able to use `go install` or `go build` if you have Go installed (`go install` requires $GOPATH to be configured)

**Comment by fordrink** [comment]
I have already installed PATH, this is an example of your gxss


![2022-07-16_14-23](https://user-images.githubusercontent.com/74085414/179367954-73b69cfa-c60b-40ce-a9d2-de2ccaeae6d7.png)

**Comment by fordrink** [comment]
Hi @garlic0x1 [garlic0x1](https://github.com/garlic0x1)

Can you tell me please step by step install?

**Comment by garlic0x1** [comment]
I just installed it on a fresh docker container, here were the steps I took  

First I created a fresh machine with Go properly installed.  
```
sudo docker run -it golang:latest
```
Then you will be given an interactive shell to the container.  

Then I cloned and installed the repository in the container.
```
git clone https://github.com/garlic0x1/php-analyzer.git
cd php-analyzer
go install
```

Now the application is installed. Here is me using it after fresh install
```
$ echo jxss.php | php-analyzer -yaml
file: jxss.php
type: xss
path:
- stack: '[assign] $article_name <- [taint] $_GET'
  code: $article_name = $_GET['article'] 22:479
- stack: '[sink] die <- [taint] $article_name'
  code: die($article_name) 24:573
...
...
...
```

**Comment by fordrink** [comment]
I got it, thank you so much.
